ports:
  - port: 8080

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Pivotal.vscode-spring-boot@1.21.0:VrPD7WUvW3BLuex1cvs7Sg==
    - PKief.material-icon-theme@4.3.0:URe4ANXBLYHzB6CeGyTN8A==